### ISSUE TITLE
Typings and SET Clarification

### ISSUE THREAD

**Issue by alixaxel** [fent/ret.js#16]
I'm currently updating my [`genex`](https://www.npmjs.com/package/genex) package to Typescript and while writing typings for `ret` I noticed this strange mention in the documentation that doesn't seem to make sense to me:

> **SET** Contains a key set specifying what tokens are allowed and a key not specifying if the set should be negated. A set can contain other sets, ranges, and characters.

In which cases would a `SET` token return other `SET` tokens? I can't think of an example for this.

---

Also, regarding typings, would you be willing to bundle them if I submit a PR? I currently have this:

```ts
declare function ret(input: string): ret.Root;

declare namespace ret {
  enum types {
    ROOT = 0,
    GROUP = 1,
    POSITION = 2,
    SET = 3,
    RANGE = 4,
    REPETITION = 5,
    REFERENCE = 6,
    CHAR = 7,
  }

  type Token = Group | Position | Set | Range | Repetition | Reference | Char;
  type Tokens = Root | Token;

  type Root = {
    type: types.ROOT;
    stack?: Token[];
    options?: Token[][];
  };

  type Group = {
    type: types.GROUP;
    remember: boolean;
    followedBy: boolean;
    notFollowedBy: boolean;
    stack?: Token[];
    options?: Token[][];
  };

  type Position = {
    type: types.POSITION;
    value: "^" | "$" | "B" | "b";
  };

  type Set = {
    type: types.SET;
    set: (Set | Range | Char)[];
    not: boolean;
  };

  type Range = {
    type: types.RANGE;
    from: number;
    to: number;
  };

  type Repetition = {
    type: types.REPETITION;
    min: number;
    max: number;
    value: Token;
  };

  type Reference = {
    type: types.REFERENCE;
    value: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
  };

  type Char = {
    type: types.CHAR;
    value: number;
  };
}

export = ret;
```

**Comment by alixaxel** [comment]
Okay, seems like something like `/[\D\d]/` yields a set within a set, ignore my question please. :)

**Comment by fent** [comment]
Typings are welcomed. I might convert some of my packages to typescript in the future, including this one.

**Comment by alixaxel** [comment]
@fent Great! Just opened a PR.
