### ISSUE TITLE
Feature Request - Abiltiy to Simplify

### ISSUE THREAD

**Issue by alixaxel** [fent/ret.js#18]
Taking a hint from Golang, the `regexp/syntax` offers a [`Simplify`](https://golang.org/pkg/regexp/syntax/#Regexp.Simplify) method.

I know it's not trivial, but it would be super useful to have this in `ret.js` as well.

Advanced simplifications / optimizations are not as useful as redundant ones, for instance:

```
/(a|a|a)/ => /(a)/
/(a+)+/ => /(a+)/
/a{0,2}?/ => /a{0,2}/
/(a{0,2})?/ => /(a{0,2})/
/(?:a+)+/ to /(?:a)+/
```

**Comment by fent** [comment]
This sounds like it would be suited for another library on top of ret. This library's goal is only to parse regex as is.

As an example, here's a couple of libraries that use ret and do additional processing on the tokens.

https://www.npmjs.com/package/safe-regex2
https://www.npmjs.com/package/genex

**Comment by alixaxel** [comment]
Haha, yeah - at least now I know it's example-worthy! :smile: 

Fair enough, I did implement [distinct groupings](https://github.com/alixaxel/genex.js/blob/master/source/index.ts#L43-L47) and I took a [jab at quantifiers](https://github.com/alixaxel/genex.js/blob/40641a38bf8403fb66c3b1d5b37482c306d4e723/source/index.ts#L95-L99) (mostly non-greedy).

With these additions I only have [one failing test](https://github.com/alixaxel/genex.js/blob/40641a38bf8403fb66c3b1d5b37482c306d4e723/tests/genex.test.ts#L96), which considering how edgy is it, I think it's fine.
