### ISSUE TITLE
`[^.]`, `[^\.]` and `[^\\.]` have the same token

### ISSUE THREAD

**Issue by jeswr** [fent/ret.js#27]
`[^.]`, `[^\.]` and `[^\\.]` all tokenize to
```ts
{
  "type":0,
  "stack":
    [{
      "type":3,
      "set":
        [{
          "type":7,
          "value":46
         }],
       "not":true
    }]
}
```

**Comment by charmander** [comment]
Are these in JavaScript string literals? `"[^.]" === "[^\.]"`, and the regular expressions `"[^.]"` and `"[^\\.]"` are equivalent.

**Comment by jeswr** [comment]
Oh right my bad, I made the mistake thinking that [.] was doing a match all as opposed to just matching the character.
