### ISSUE TITLE
[BUG]: Cannot handle references with value greater than 10

### ISSUE THREAD

**Issue by jeswr** [fent/ret.js#38]
If I have an expression `/...\10/` the reference will be parsed as '1' rather than '10'. This is confirmed by the fact that [here](https://github.com/fent/ret.js/blob/efb9f07070402962192277189e99f9b700c85b70/lib/tokenizer.ts#L73) only one digit is tested.

**Comment by fent** [comment]
for whatever reason, i assumed this only went up to 9 when i first made this. but a quick test in the console revealed that it does go to past it

![image](https://user-images.githubusercontent.com/933490/148344818-3c746805-0ed7-4db7-bc5d-533a6f2f1898.png)

**Comment by jeswr** [comment]
Yep - the behavior appears to be that it goes to the number of capturing groups that are *available* and if there are no more capturing groups, then it is treated as a value (well this is what firefox does at least...).

![image](https://user-images.githubusercontent.com/63333554/148369859-4661beae-b066-4518-b6e2-25196b241266.png)
