### ISSUE TITLE
Documentation doesn't match behavior

### ISSUE THREAD

**Issue by davisjam** [fent/ret.js#8]
I've noticed some discrepancies between the docs and the actual behavior.

Here's my test script:

```
var ret = require('ret');

console.log(ret.types);

var regexes = [/foo|bar/, /abc/, /(a+)+/, /(aa+)+/, /(a+){40}$/];
regexes.forEach(function(re) {
  var pattern = re.source;
  var tokens = ret(pattern);

  console.log('pattern: /' + pattern + '/ , tokens: ' + JSON.stringify(tokens, null, 2));
});
```

This produces plenty of output, including:

```
pattern: /(a+)+/ , tokens: {
  "type": 0,
  "stack": [
    {
      "type": 5,
      "min": 1,
      "max": null,
      "value": {
        "type": 1,
        "stack": [
          {
            "type": 5,
            "min": 1,
            "max": null,
            "value": {
              "type": 7,
              "value": 97
            }
          }
        ],
        "remember": true
      }
    }
  ]
}
```

This illustrates several discrepancies:
1. The 'max' field for the repetition is 'null', not 'Infinity'. This seems to be a JSON thing, since the source clearly sets the value of max to 'Infinity'.
2. The 'value' field for the REPETITION token type is not stated in the docs.
3. The GROUP token type seems to have either a 'stack' or an 'options' field. This is not clear in the docs.

**Comment by fent** [comment]
Hi

> The 'max' field for the repetition is 'null', not 'Infinity'. This seems to be a JSON thing, since the source clearly sets the value of max to 'Infinity'.

Right

> The 'value' field for the REPETITION token type is not stated in the docs.

Updated

> The GROUP token type seems to have either a 'stack' or an 'options' field. This is not clear in the docs.

I've updated the readme a bit with a more thorough example of what the tokens would look like with both `stack` and `options`.

**Comment by davisjam** [comment]
Great, this is much clearer. Thanks!
