### ISSUE TITLE
npm README is out of sync with GitHub README

### ISSUE THREAD

**Issue by davisjam** [fent/ret.js#9]
Parsing (.+)\1+ yields, among other things, this REPETITION token with a value field. I don't see this in the docs.

```
        {   
            "type": 5,
            "min": 1,
            "max": null,
            "value": {
                "type": 6,
                "value": 1
            }   
        } 
```

**Comment by fent** [comment]
There is a `value` field? https://github.com/fent/ret.js#repetition

**Comment by davisjam** [comment]
I must be going blind. Thanks.

**Comment by davisjam** [comment]
Ahha, found it. The npm README seems to be out of sync with the GitHub version.

**Comment by fent** [comment]
Oh.... I wasn't aware npm showed the readme for the latest published version. I usually don't publish a new version if all I'm changing is the readme.

Thanks. I'll publish a new version for this, and also check some of my other modules.

**Comment by fent** [comment]
Ok, new version published. https://www.npmjs.com/package/ret
